git:
  depth: false
  quiet: true
sudo: required
services:
  - docker
language: java
jdk: openjdk8
addons:
  apt:
    packages:
      - jq
      - sudo
      - lsof
      - curl
      - bash
      - docker-ce
      - python-py
install: true
before_install:
  - sudo pip install --upgrade httpie docker-compose >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080
script:
  - ./gradlew clean
  - ./gradlew assemble -S
  #
  - java -jar ./app/build/libs/*.war &
  - wait_for 8080
  - http :8080/actuator/ | jq '._links'
  - http :8080/actuator/health | jq '.'
  - stop_any 80 8080
  #
  - ./gradlew composeUp
  - http :8080/actuator/ | jq '._links'
  - http :8080/actuator/health | jq '.'
  - ./gradlew :test -P remote
  - ./gradlew :test -P remote -P firefox
  - ./gradlew :test -P remote -P chrome
  - ./gradlew composeDown
notifications:
  email: false
